_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: a8610938-ba2d-4f34-a473-bac1d92b4311
name: '18F Drupal dev'
mail: dev@dev.dev
slogan: 'A thing for bootstrapping a Drupal site in Docker'
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
